#!/bin/bash
cd /opt/
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz"
tar xzf jdk-8u201-linux-x64.tar.gz
cd jdk1.8.0_201/
alternatives --install /usr/bin/java java /opt/jdk1.8.0_201/bin/java 2
alternatives --config java

# 	There are 3 programs which provide 'java'.
#
#	Selection    Command
# -----------------------------------------------
#	   1           /opt/jdk1.8.0_45/bin/java
# 	*  2           /opt/jdk1.8.0_144/bin/java
#  	 + 3           /opt/jdk-11/bin/java
#  	   4           /opt/jdk1.8.0_201/bin/java
#
# Enter to keep the current selection[+], or type selection number: 4

alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_201/bin/jar 2
alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_201/bin/javac 2
alternatives --set jar /opt/jdk1.8.0_201/bin/jar
alternatives --set javac /opt/jdk1.8.0_201/bin/javac
java -version

echo "export JAVA_HOME=/opt/jdk1.8.0_201" >> ~/.bashrc
echo "export JAVA_HOME=/opt/jdk1.8.0_201" >> ~/etc/environment

echo "export JRE_HOME=/opt/jdk1.8.0_201/jre" >> ~/.bashrc
echo "export JRE_HOME=/opt/jdk1.8.0_201/jre" >> ~/etc/environment

echo "export PATH=$PATH:/opt/jdk1.8.0_201/bin:/opt/jdk1.8.0_201/jre/bin" >> ~/.bashrc
echo "export PATH=$PATH:/opt/jdk1.8.0_201/bin:/opt/jdk1.8.0_201/jre/bin" >> ~/etc/environment


